### PR TITLE
TPP-00135: Populate existing marked dates in log multiple dates

### PR DESCRIPTION
**Pull request by faye-tan**
- dates with period marked appear on the log multiple dates screen
- changed color to red, same color as used by FLOW=MEDIUM filter by TPP's request
- changed text in header
Screen Shot 2022-04-16 at 4 34 01 PM

- made changes to LogMultipleDayPeriod to also set flow=null on newly unmarked dates
- unsaved modal only pops up when there's a change. so if you select & deselect the same date then close, no warning modal
 
#135

### CODE REVIEW

**Review by roylin2000 — COMMENTED** [review]
Minor bug that doesn't need to be fixed right away: if you log a period on a date that's in the future, it will stay red in the pick multiple dates screen. But at least it's not being logged on the actual calendar.

**Comment by faye-tan** [comment]
> Minor bug that doesn't need to be fixed right away: if you log a period on a date that's in the future, it will stay red in the pick multiple dates screen. But at least it's not being logged on the actual calendar.

@roylin2000 I will be disabling future dates in another PR tomorrow (on both the calendar and log multiple period dates screen) so this won't ever happen

**Comment by roylin2000** [comment]
> > Minor bug that doesn't need to be fixed right away: if you log a period on a date that's in the future, it will stay red in the pick multiple dates screen. But at least it's not being logged on the actual calendar.
> 
> @roylin2000 I will be disabling future dates in another PR tomorrow (on both the calendar and log multiple period dates screen) so this won't ever happen

Oh that's perfect! I will approve then :)

**Review by roylin2000 — APPROVED** [review]
Works well and code looks good!

**Pull request merged**
